# Generated by Django 3.2.7 on 2021-10-28 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carrear',
            fields=[
                ('idcarrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('idchat', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Coments',
            fields=[
                ('idcoment', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('files', models.FileField(blank=True, null=True, upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='stateMessage',
            fields=[
                ('idstateMessage', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeNotification',
            fields=[
                ('idtypenotification', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='typePost',
            fields=[
                ('idtypePost', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('iduser', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nickname', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('age', models.DateTimeField()),
                ('typeCarrear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdChuntels.carrear')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('idwork', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('files', models.FileField(blank=True, null=True, upload_to='files/')),
                ('cocreators', models.ManyToManyField(related_name='cocreatorsWork', to='bdChuntels.User')),
                ('coments', models.ManyToManyField(related_name='comentsWork', to='bdChuntels.User')),
                ('likes', models.ManyToManyField(related_name='likesWork', to='bdChuntels.User')),
                ('typePost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdChuntels.typepost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdChuntels.user')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('idpost', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('files', models.FileField(blank=True, null=True, upload_to='files/')),
                ('coments', models.ManyToManyField(related_name='comentsPost', to='bdChuntels.User')),
                ('likes', models.ManyToManyField(related_name='likesPost', to='bdChuntels.User')),
                ('typePost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdChuntels.typepost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdChuntels.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('idnotification', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiverNotification', to='bdChuntels.user')),
                ('typeNotification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdChuntels.typenotification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdChuntels.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('idmessage', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('files', models.FileField(blank=True, null=True, upload_to='files/')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdChuntels.chat')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiverMessage', to='bdChuntels.user')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdChuntels.statemessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdChuntels.user')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('idlike', models.AutoField(primary_key=True, serialize=False)),
                ('coment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdChuntels.coments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdChuntels.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdChuntels.user')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('idfriend', models.AutoField(primary_key=True, serialize=False)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='bdChuntels.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personUser', to='bdChuntels.user')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('idfollow', models.AutoField(primary_key=True, serialize=False)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='bdChuntels.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdChuntels.user')),
            ],
        ),
        migrations.AddField(
            model_name='coments',
            name='likes',
            field=models.ManyToManyField(related_name='likesComents', to='bdChuntels.User'),
        ),
        migrations.AddField(
            model_name='coments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentsPost', to='bdChuntels.post'),
        ),
        migrations.AddField(
            model_name='coments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdChuntels.user'),
        ),
        migrations.AddField(
            model_name='chat',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiverChat', to='bdChuntels.user'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdChuntels.user'),
        ),
    ]
