# Generated by Django 3.2.7 on 2021-10-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdChuntels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='fotosPerfil'),
        ),
    ]
