# Generated by Django 3.2.7 on 2021-10-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdChuntels', '0002_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='state',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='fotosPerfil/'),
        ),
    ]
