# Generated by Django 3.2.7 on 2021-10-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdChuntels', '0003_auto_20211028_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='state',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
