# Generated by Django 3.2.7 on 2021-11-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdChuntels', '0005_auto_20211103_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='coment',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AlterField(
            model_name='coments',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likesComents', to='bdChuntels.User'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likesPost', to='bdChuntels.User'),
        ),
        migrations.AlterField(
            model_name='work',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likesWork', to='bdChuntels.User'),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
