# Generated by Django 3.2.7 on 2021-11-18 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdChuntels', '0006_auto_20211118_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentsWorks',
            fields=[
                ('idcoment', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('files', models.FileField(blank=True, null=True, upload_to='files/')),
                ('likes', models.ManyToManyField(blank=True, related_name='likesComentsWorks', to='bdChuntels.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdChuntels.user')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentsWorks', to='bdChuntels.work')),
            ],
        ),
    ]
