# Generated by Django 3.2.7 on 2021-12-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdChuntels', '0007_comentsworks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.AlterField(
            model_name='message',
            name='state',
            field=models.CharField(blank=True, default='1', max_length=1, null=True),
        ),
    ]
