# Generated by Django 3.2.7 on 2021-12-30 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdChuntels', '0008_auto_20211129_1735'),
        ('bdChuntels', '0008_auto_20211223_2332'),
    ]

    operations = [
    ]
