# Generated by Django 3.2.7 on 2021-12-30 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdChuntels', '0009_merge_0008_auto_20211129_1735_0008_auto_20211223_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='state',
            field=models.CharField(blank=True, default='1', max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('idfile', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('files', models.FileField(blank=True, null=True, upload_to='files/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdChuntels.user')),
            ],
        ),
    ]
